extends: airbnb
installedESLint: true
plugins:
  - react
rules:
  no-console: 0
  no-param-reassign: 0
  semi: [2, "never"]
  radix: ["error", "as-needed"]
  jsx-quotes: ["error", "prefer-single"]
  no-else-return: "off"

globals:
  FileReader: true
  fetch: true

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
      jsx: true
      experimentalObjectRestSpread: true
